version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production # Remove this line if you want to use the NODE_ENV from .env.local
