version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - fullstack

  server:
    build: ./server
    ports:
      - "9000:9000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - fullstack

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - fullstack

networks:
  fullstack:
