version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80" # This will map port 80 in the container to port 8080 on your host machine

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:8080" # If the Flask app runs on port 8080 inside the container
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
